[tool.poetry]
name = "diplom"
version = "0.1.0"
description = ""
authors = ["Wildtsk <wildtsk@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
